server:
  port: 8091
  tomcat:
    threads:
      max: 200        # 设定处理客户请求的线程的最大数目，决定了服务器可以同时响应客户请求的数,默认200
      min-spare: 50   # 初始化线程数,最小空闲线程数,默认是10
    accept-count: 10  # 等待队列长度

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfigurationV2
      # 如需使用 RabbitMQ 就开开这个
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://${HOST_IP}:${MYSQL_PORT}/achobeta_refine?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 15 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 25 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  mail: #邮件验证码配置
    host: smtp.qq.com  # SMTP服务器地址（QQ邮箱固定）
    port: 587          # 端口（587为加密端口）
    username: ${MAIL_SMTP_USERNAME}
    password: ${MAIL_SMTP_PASSWORD}
    properties.mail.smtp.auth: true  # 启用身份验证
    properties.mail.smtp.starttls.enable: true  # 启用TLS加密

# Redis【如需使用请打开】
redis:
  sdk:
    # 开关
    enabled: true
    config:
      host: ${HOST_IP}
      port: ${REDIS_PORT}
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

# MyBatis 配置【如需使用记得打开】
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

email:
  config:
    verify-code-expire-minute: 5

langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: ${DASH_SCOPE_API_KEY}
      streaming-chat-model:
        model-name: qwen-max
        api-key: ${DASH_SCOPE_API_KEY}

jwt:
  secret: ${JWT_SECRET}
  access-token-ttl: 2h
  refresh-token-ttl: 2d

ai:
  dashscope:
    max-concurrency: ${AI_MAX_CONCURRENCY}  # 根据实际需求设置合适的并发数
