# /usr/local/bin/docker-compose -f /docs/dev-ops/docker-compose-app.yml up -d
version: '3.8'
# docker-compose -f docker-compose-app.yml up -d
# 你需要修改system为你自身系统的仓库名
services:
  refine:
    image: docker.cnb.cool/hamster-yhz/refine:latest
    container_name: refine
    restart: on-failure
    ports:
      - "8091:8091"
    env_file:
      - ./.env
    environment:
      - TZ=PRC
      - SERVER_PORT=8091
      - APP_CONFIG_CROSS_ORIGIN=*
      - REDIS_SDK_CONFIG_HOST=redis
      - REDIS_SDK_CONFIG_PORT=6379
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge